apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask
spec:
  containers:
  - name: flask-container
    image: stratcastor/trio-flask:latest
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: ClusterIP 
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000